# Generated by Django 3.2 on 2022-04-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('unique_hash', models.CharField(max_length=20, unique=True)),
                ('tx_hash', models.CharField(max_length=34, unique=True)),
            ],
        ),
    ]
